### ISSUE TITLE
libcwd / cmake / hunter

### ISSUE THREAD

**Issue by cs224** [CarloWood/libcwd#1]
Dear Carlo, I tried to contact you via mail, but perhaps this mail landed in the spam folder. Therefore the same question now via a github issue:

I have a question: I was looking into a way to build my C++ project together with its dependencies in a similar way like Java maven does, e.g. just pointing my build system to an external library and the build system does the rest. This is also similar like Rust crates work.

I searched around and found in the C++ world only one tool that looked like what I was looking for: hunter: https://docs.hunter.sh/en/latest/
I use its mechanisms to integrate GTest into my build.

I am not fixed on hunter, e.g. if there are other/better tools out there that fit the bill I am happy, too. I only did not find other tools.

Hunter also fits quite well, because I've chosen for the moment to use the CLion IDE (because I am used to IntelliJ Idea for Java), which also is based on cmake.

I am new to cmake, hunter, clion, c++ (since c++11 it is like a different language).

So now my core question: what would you propose is the most straight forward way to integrate libcwd into my build like hunter does? And if you believe that hunter is a good (enough) solution: would you support the idea of "hunterizing" libcwd: 
https://docs.hunter.sh/en/latest/creating-new.html

Thanks,
Christian

**Comment by CarloWood** [comment]
Hi Christian, I did reply the first time... Here is what I wrote:

Hi Christian!

It is very nice to hear from someone who is happy with my library :)
I get basically zero mails on my projects (any); and I'm never sure
if that is because they "just work" (as I always strive hard for),
or that nobody is using them :(.

Before I go into your question, I'd like you to study two things that
I wrote. That is; if you have any questions about them feel free
to mail me and I will answer them.

Firstly, did you know that this exists:

https://github.com/CarloWood/cwds

This is a git submodule that would get compiled along with your
project and provides stuff that I found to be so common between
projects that I turned it in to a git submodule for easy sharing
between projects. Hmm, I see I need to update the README...
Using this submodule the correct way to use libcwd would be:

int main()
{
  Debug(NAMESPACE_DEBUG::init());

Aka, the DEBUGGLOBAL stuff was moved into that init() call.

As always, every source file that uses libcwd should start with
#include "sys.h". cwds comes with a default sys.h (and debug.h),
so in most cases you don't need to provide them yourself anymore.
That is, the include path is such that any existing sys.h or
debug.h in the root of your project will get picked up first,
but there isn't any it will use cwds/sys.h and/or cwds/debug.h.

There is also an easier way to support adding new custom debug
channels. The correct way to add a new debug channel is now to
add

#ifdef CWDEBUG
NAMESPACE_DEBUG_CHANNELS_START
extern channel_ct my_channel;
NAMESPACE_DEBUG_CHANNELS_END
#endif

to whatever header file of yours seems to most logical (or
to add it to your debug.h file). And then add

#ifdef CWDEBUG
NAMESPACE_DEBUG_CHANNELS_START
channel_ct my_channel;
NAMESPACE_DEBUG_CHANNELS_END
#endif

to the corresponding .cpp file (this is correctly described in the
README).


Furthermore, you ask "what would you propose is the most straight 
forward way to integrate libcwd into my build like hunter does?"

What I use exclusively myself these days is this:

https://github.com/CarloWood/cwm4

And if your project is using autoconf/automake then that
would definitely be what I'd recommend ;).

All my submodules are plug&play this way: you just do a
'git submodule add ...' and that's it (well, almost, you
still need to add the CXXFLAGS and LDADD flags to have
programs link with the submodules. As an example, have a
look at the submodule https://github.com/CarloWood/ai-utils

If the license of cwds and/or cwm4 is a problem then I'm
willing to change that-- not sure if I want to change the
licenses of the existing submodules that I wrote ;).

Regards,
Carlo

PS cwds comes with benchmarking tools that I believe only
work on 64bit intel. That is, it contains some assembly code
that is for such platforms. If that were a problem then
you'd have to manually remove the benchmarking code from it
or fix it yourself ;) (I'd actually welcome a fix for 32bit!)
Here is some random code that is using this benchmarking
stuff:
https://github.com/CarloWood/ai-statefultask-testsuite/blob/master/src/mutex_benchmark.cxx

**Comment by cs224** [comment]
Thanks a lot Carlo for your exhaustive response!
This is just fyi: I just checked and I really could not find your reply, also not in the spam filter. Not sure what happened there.

I was not aware of cwds and your submodule mechanism. I'll look into this! I'll have some work in front of me now :)
